<?php

class Job
{
    private $db;

    public function __construct()
    {
        $this->db = Database::getInstance()->getConnection();
    }

    // Lookup Employer ID based on the authenticated User ID
    public function getEmployerIdByUserId($userId)
    {
        $sql = "SELECT employer_id FROM employers WHERE user_id = :user_id LIMIT 1";
        $stmt = $this->db->prepare($sql);
        $stmt->execute([':user_id' => $userId]);
        $result = $stmt->fetch();
        return $result ? $result['employer_id'] : false;
    }

    public function getMasterSkills()
    {
        // V2 Upgrade: Join with categories to allow organized UI rendering
        $sql = "SELECT ms.skill_id, ms.skill_name, sc.category_name 
                FROM master_skills ms
                LEFT JOIN skill_categories sc ON ms.category_id = sc.category_id
                WHERE ms.status = 'approved'
                ORDER BY sc.category_name ASC, ms.skill_name ASC";
        $stmt = $this->db->prepare($sql);
        $stmt->execute();
        return $stmt->fetchAll();
    }

    // Fetch all active job seekers to feed into the AI Engine loop
    public function getActiveJobSeekers()
    {
        $sql = "SELECT js.jobseeker_id 
                FROM job_seekers js
                JOIN users u ON js.user_id = u.user_id
                WHERE u.account_status = 'Active'";
        $stmt = $this->db->prepare($sql);
        $stmt->execute();
        return $stmt->fetchAll();
    }

    public function createJobPosting($employerId, $jobData, $selectedSkills)
    {
        try {
            $this->db->beginTransaction();

            // 1. Core job row. Schema v2 columns: min_years_experience
            //    (TINYINT UNSIGNED, an integer count of years — replaces the
            //    dropped free-text required_experience, C-38) and
            //    work_arrangement (ENUM, stored not scored — C-39, M2 BR-5).
            //    The controller has already whitelisted every enum value and
            //    range-checked the integer, so an invalid value never reaches
            //    here as a silent NULL.
            $sqlJob = "INSERT INTO job_postings
                (employer_id, job_title, job_description, min_years_experience, salary_range,
                 employment_type, work_arrangement, municipality_id, job_status)
                VALUES
                (:employer_id, :job_title, :job_description, :min_years_experience, :salary_range,
                 :employment_type, :work_arrangement, :municipality_id, 'Open')";

            $stmtJob = $this->db->prepare($sqlJob);
            $stmtJob->execute([
                ':employer_id'          => $employerId,
                ':job_title'            => $jobData['job_title'],
                ':job_description'      => $jobData['job_description'],
                ':min_years_experience' => $jobData['min_years_experience'],
                ':salary_range'         => $jobData['salary_range'],
                ':employment_type'      => $jobData['employment_type'],
                ':work_arrangement'     => $jobData['work_arrangement'],
                ':municipality_id'      => $jobData['municipality_id'],
            ]);

            // 2. Securely fetch the exact auto-incremented job_id generated by the previous query
            $newJobId = $this->db->lastInsertId();

            // 3. Required skills — requirement_type is Mandatory / Preferred
            //    only ('Optional' does not exist in this system — CLAUDE.md,
            //    M2 BR-1, C-20). A pending-status skill still inserts here; it
            //    is filtered out of scoring by AIEngineService (C-42).
            $sqlSkill = "INSERT INTO job_required_skills (job_id, skill_id, requirement_type)
                         VALUES (:job_id, :skill_id, :req_type)";
            $stmtSkill = $this->db->prepare($sqlSkill);

            foreach ($selectedSkills as $skillId => $reqType) {
                $stmtSkill->bindValue(':job_id', $newJobId);
                $stmtSkill->bindValue(':skill_id', $skillId);
                $stmtSkill->bindValue(':req_type', $reqType);
                $stmtSkill->execute();
            }

            $this->db->commit();

            // Return the newly created job_id so the Controller can trigger the AI engine in Part 3
            return $newJobId;

        } catch (Throwable $e) {
            if ($this->db->inTransaction()) {
                $this->db->rollBack();
            }
            error_log("Job Posting Transaction Failed: " . $e->getMessage());
            return false;
        }
    }

    public function getOpenJobDetails($jobId)
    {
        // province_name lives on lib_provinces in schema v2, not on
        // lib_municipalities — the join is mandatory (same fix
        // Profile::getMunicipalities() carries). Without it this query 500s and
        // a seeker cannot open a vacancy from the feed (UC-05 step 15).
        $sql = "SELECT jp.*, e.company_name, e.company_logo, e.company_description,
                       m.municipality_name, p.province_name
                FROM job_postings jp
                JOIN employers e ON jp.employer_id = e.employer_id
                LEFT JOIN lib_municipalities m ON jp.municipality_id = m.municipality_id
                LEFT JOIN lib_provinces p ON m.province_id = p.province_id
                WHERE jp.job_id = :job_id AND jp.job_status = 'Open' LIMIT 1";
        $stmt = $this->db->prepare($sql);
        $stmt->execute([':job_id' => $jobId]);
        return $stmt->fetch(PDO::FETCH_ASSOC);
    }

    /**
     * Fetch recent open jobs for the public landing page.
     */
    public function getFeaturedJobs($limit = 3)
    {
        $sql = "SELECT jp.*, e.company_name, e.company_logo,
                       m.municipality_name, p.province_name
                FROM job_postings jp
                JOIN employers e ON jp.employer_id = e.employer_id
                LEFT JOIN lib_municipalities m ON jp.municipality_id = m.municipality_id
                LEFT JOIN lib_provinces p ON m.province_id = p.province_id
                WHERE jp.job_status = 'Open'
                ORDER BY jp.date_posted DESC, jp.job_id DESC
                LIMIT :limit";
        $stmt = $this->db->prepare($sql);
        $stmt->bindValue(':limit', (int)$limit, PDO::PARAM_INT);
        $stmt->execute();
        return $stmt->fetchAll(PDO::FETCH_ASSOC);
    }
}